### ISSUE TITLE
Audio playback in demo

### ISSUE THREAD

**Issue by tcdaly** [AaronDavidNewman/Smoosic#21]
I can hear individual notes being played in the demo, but is there any way of playing back the whole line?

**Comment by AaronDavidNewman** [comment]
I'm not understanding the difference between 'individual notes' and 'whole line'.  Doesn't playing the individual notes in sequence constitute the line?

**Comment by AaronDavidNewman** [comment]
Oh...I see.  Sorry, 'p' to play, 's' to stop.  Also the play button:
![image](https://user-images.githubusercontent.com/5438280/83648040-319aa400-a57b-11ea-98af-0f4b6c8c7869.png)

**Comment by tcdaly** [comment]
Thanks.  Keyboard shortcuts 'p' and 's' work.  What I'm still puzzled by is that I don't see the play, pause and stop buttons in the UI:
![smoosic](https://user-images.githubusercontent.com/4974660/83651060-f87d2680-a5b0-11ea-8227-fc79398d4c6f.png)

**Comment by tcdaly** [comment]
I see now, you have to click on the mixer icon.
