### ISSUE TITLE
add or remove measures / bars

### ISSUE THREAD

**Issue by rkr1209** [AaronDavidNewman/Smoosic#22]
Hi,
how can I add or remove measures / bars?
thanks

**Comment by AaronDavidNewman** [comment]
Insert to add, shift-insert to add after, delete to delete.

**Comment by rkr1209** [comment]
most of us are on OSX which doesn't have an insert key. Is it possible for you to change the shortkey or to add menu controls for "add" and "remove" measures?

**Comment by AaronDavidNewman** [comment]
You're right!  Thanks for reporting that.
I added Ctrl-i, shift-ctrl-I, and ctrl-d for equivalent keyboard strokes.  I also expanded the measure button on the left to include adding/deleting from the UI.

**Comment by rkr1209** [comment]
works perfect! Thanks!
Can we connect to discuss more about some features, UI and translations?

**Comment by AaronDavidNewman** [comment]
yeah, absolutely.  I'd welcome any contributions, and any more Mac bugs you find are also appreciated.

**Comment by techinventiverohit** [comment]
I am using this with the ckeditor. I am not able to type anything in the editor because key is bind with the piano. Can we enable and disable using button?

**Comment by AaronDavidNewman** [comment]
@techinventiverohit  can you create a new issue for this?  This should be possible, but it deserves its own thread.
