### ISSUE TITLE
I want to load json from the DB in editor.

### ISSUE THREAD

**Issue by vgulshan1985** [AaronDavidNewman/Smoosic#24]
Hi @AaronDavidNewman ,

Hope you are well.

I wan to load the Json in editor which is saved in DB.

Can you help in that?

Also what is the best way to store Json not the SVG in DB?

Please explain.

Thanks for this Plugin. 

Thanks,
Gulshan

**Comment by AaronDavidNewman** [comment]
SmoScore.serialize method creates JSON.  Look in fileDialog.js at the save function.  You can just send it to a server via XHR call and store it as a blob.

``` javascript
    var txt = this.layout.score.serialize();
    txt = JSON.stringify(txt);

**Comment by AaronDavidNewman** [comment]
@vgulshan1985  if this is answered I will close this ticket
