### ISSUE TITLE
Need Save Button like File button

### ISSUE THREAD

**Issue by vgulshan1985** [AaronDavidNewman/Smoosic#25]
Hi @AaronDavidNewman,

I want to add  Save Button Left left side Like File.

Functionality will remain same as we have under File menu.

You can see in attached screen shot: 

Thanks,
Gulshan
![image_2020_08_06T12_34_29_887Z](https://user-images.githubusercontent.com/7002085/89532496-7e1a8e00-d80f-11ea-835c-dfe176ec6361.png)

**Comment by vgulshan1985** [comment]
> Hi @AaronDavidNewman,
> 
> I want to add Save Button Left left side Like File.
> 
> Functionality will remain same as we have under File menu.
> 
> You can see in attached screen shot:
> 
> Thanks,
> Gulshan
> ![image_2020_08_06T12_34_29_887Z](https://user-images.githubusercontent.com/7002085/89532496-7e1a8e00-d80f-11ea-835c-dfe176ec6361.png)

@AaronDavidNewman Can you please help in that?
Help will be appreciated.

Thanks,
Gulshan

**Comment by AaronDavidNewman** [comment]
In defaultRibbon.js, you can add a button to the leftButtons like:

``` javascript
			 {
				leftText: 'Save Answer',
				rightText: '',
				icon: '',
				classes: 'icon ',
				action: 'modal',
				ctor: 'SuiSaveFileDialog',
				group: 'scoreEdit',
				id: 'saveAnswerModal'
			}
```

And also add the saveAnswerModal id to the left button array.

**Comment by vgulshan1985** [comment]
Thanks a lot @AaronDavidNewman It really helped.
