### ISSUE TITLE
how to fix position drag draganime  div on small screen 

### ISSUE THREAD

**Issue by gmirza786** [AaronDavidNewman/Smoosic#27]
Hi @AaronDavidNewman,

hope you doing Well!

I want to fix  draganime   left  position  on small screen

<div class="draganime hide" aria-hidden="true" style="width: 390px; height: 399.65px; left: 643px; top: 54px;"></div>
please help me 

You can see in attached screen shot:

![image](https://user-images.githubusercontent.com/69457491/89769197-5d597d80-db1a-11ea-9cc0-63933f7525f4.png)

Thanks,
Gulfam Mirza

**Comment by vgulshan1985** [comment]
@AaronDavidNewman 

I am also having same issue. Can you please help in that too?

Thanks,
Gulshan

**Comment by AaronDavidNewman** [comment]
I'm sorry guys I'm not following what the problem is.  Can you maybe post an animated GIF.  Also, what is the resolution where you start seeing this?

**Comment by gmirza786** [comment]
Yes Sure 

I request to you 
please provide me better solution
Thank You!
See This
![Bildschirmvideo-aufnehmen-2020-08-05-um-16 23 46](https://user-images.githubusercontent.com/69457491/89987568-e6e48900-dc9b-11ea-9d32-7e8fac51a3e5.gif)

**Comment by vgulshan1985** [comment]
@AaronDavidNewman Same issue is happening on my side. Can you please help in that?

**Comment by vgulshan1985** [comment]
@AaronDavidNewman Can you please check to this and  help ?

**Comment by AaronDavidNewman** [comment]
Sorry guys, I thought I responded to this, but I don't see it.  Maybe forgot to save.

I don't see this in Smoosic no matter how small I make the screen, so I'm guessing this has to do with your custom changes and not screen size.  In my application, the divs: .attributeDialog' and  '.draganime' are at the same level in the DOM, and origin at offset left:0, top:0 of the web page.  So when you drag, the logic uses the same offset value of '.attributeModal' on '.draganime'.  If these offsets are different in your DOM, you need to make that adjustment in the dragging logic in htmlHelpers.draggable.

Also, make sure the parent containers of these divs are position:relative, so the position:absolute does the expected thing.  In Smoosic this is '.dom-container'.  It looks like the value of the dialog itself in '.attributeModal .attributeDialog' is calculated correctly, so once you make this change you should be OK.

![SmoosicDOM](https://user-images.githubusercontent.com/5438280/90421157-9647a400-e07e-11ea-9a5f-245e3c0f8a58.PNG)

**Comment by vgulshan1985** [comment]
@AaronDavidNewman 
Please check here

http://lcmetest.exsrv.com/mod/quiz/attempt.php?attempt=51&cmid=15

User: admin
Password: Admin@123

Thanks,
Gulshan

**Comment by AaronDavidNewman** [comment]
Here's your problem:

![SmoosicDomLeft](https://user-images.githubusercontent.com/5438280/90427917-d4e25c00-e088-11ea-9795-7eb3f73819ac.PNG)

'!important' will win over element styles, every time.  Avoid using it - it was required in the IE6 days, not so much now.

Now the dragging scales correctly, but you still need to consider the offset so the initial position of dialog and '.anime' div are correct (treating UL of form as 0,0, instead of page 0,0).

**Comment by vgulshan1985** [comment]
@AaronDavidNewman We have made change and still it has issue. Popup has to be come in center.

**Comment by vgulshan1985** [comment]
@AaronDavidNewman  If you can help will be good., This is the last step where we are stuck.

**Comment by AaronDavidNewman** [comment]
If you pull my latest changeset, I added logic to handle .dom-container that is not at origin.  It should fix your issue also.

**Comment by AaronDavidNewman** [comment]
@vgulshan1985  how is this working, I'd like to close the ticket
