### ISSUE TITLE
Db major / Bb minor key signature

### ISSUE THREAD

**Issue by rkr1209** [AaronDavidNewman/Smoosic#39]
Hi Aaron, 

- typo: accidentals/icon not shown in key signature menu 
smoosic.js:41347
`icon: 'key-sig-bd',`
->
`icon: 'key-sig-db',`

- key signature is wrong (but unfortunately I can not find where the issue is). It displays 7 sharps instead of 5 flats. I'm sure it was correct in an earlier version from mid of last year, but don't find which update has caused this. Would be great if you could check it. :-)

Best,
R

**Comment by AaronDavidNewman** [comment]
How embarrassing!   I just pushed a PR that fixes this.

**Comment by rkr1209** [comment]
brilliant! Thanks!
