### ISSUE TITLE
OSX - Unhandled Promise Rejection: EncodingError: Decoding failed

### ISSUE THREAD

**Issue by rkr1209** [AaronDavidNewman/Smoosic#51]
Hi,

catching up to see how this great project is moving forwards, I recognized that the demo application no longer works on OSX / iOS devices using Safari.

```
Unhandled Promise Rejection: EncodingError: Decoding failed
(anonymous function)
rejectPromise
```

The error message is not really clear to me, but it seems like an issue with the audio context file?

If you find some time, it would be great if you could take a look at it.

Thanks!

**Comment by AaronDavidNewman** [comment]
Hi @rkr1209 , I just updated the application.  I tried it on both Safari and Chrome on both a Macbook and IPad.  I was able to do pretty much everything, including playback.  Can you give it a try now?

**Comment by rkr1209** [comment]
Hi @AaronDavidNewman,

this is really strange. It still gives me the same error on my iMac OSX 10.15.7, Safari 15.0.
On the other hand, it works on my iPhone using Safari and also on my Mac using Chrome or Firefox. 

https://user-images.githubusercontent.com/67444914/139576432-0febc7a0-a7dc-4112-ada3-db4d07b3200a.mp4

**Comment by AaronDavidNewman** [comment]
I am on MacOS 10.14.6/ Safari 14, and I don't think an upgrade to 10.15 is available to me.  So I may not be able to look into it for awhile.  It seems apple is doing everything it can to make Safari the IE6 of browsers.

You don't have any extensions installed on the browser, do you?  The exception might be coming from that.  I can't tell quite from the screen shot, but I don't see a call stack there from any Smoosic code.

**Comment by rkr1209** [comment]
I have no extensions installed, even on a clean machine and incognito window, the issue appears.
Like you said, I also think Apple is on it's best way to invent the new IE. 

Searching for the error message, gives some information that it is a known issue with the current Safari version, where something is wrong with decoding of files.
