### ISSUE TITLE
Microtone

### ISSUE THREAD

**Issue by odaymusic** [AaronDavidNewman/Smoosic#53]
Why did the oriental tones microtone disappear? It was something special ?

**Comment by AaronDavidNewman** [comment]
They did not disappear.  Nothing has changed, they have their own button:

![image](https://user-images.githubusercontent.com/5438280/139589064-67fdab8f-43d7-40bd-8017-b80fc116bf45.png)

![image](https://user-images.githubusercontent.com/5438280/139589082-817fafc5-1055-492d-bed6-a485777f34f9.png)

**Comment by AaronDavidNewman** [comment]
@odaymusic are you still having troubles?  If so, can you so how I can reproduce the issue?
